### ISSUE TITLE
Select Cloud Provider

### ISSUE THREAD

**Issue by pwarias** [StudyRoomsIPro/StudyRooms#1]
As a developer (I know not supposed to do it from this perspective- only for the first couple) we need to have a platform where we can build our application. I want to have a document comparing the major cloud providers in terms of pricing (for both vm, dns services and database services) and what we can run on it. This is so that we can choose the best platform to develope our project (AWS, Azure, Firebase, Github) Select Cloud Provider

**Comment by ghost** [comment]
AWS Is our Selected Cloud Provider
